name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        XIVAPI_KEY: ${{ secrets.XIVAPI_KEY }}
      run: |
        echo "Starting bot..."
        python bot/main.py